package com.mitchej123.hodgepodge.mixins.late.thaumcraft;

import net.minecraft.entity.Entity;
import net.minecraft.world.WorldServer;
import net.minecraft.world.gen.ChunkProviderServer;

import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Shadow;
import org.spongepowered.asm.mixin.Unique;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

import com.mitchej123.hodgepodge.mixins.hooks.ChunkGenScheduler;

import thaumcraft.common.lib.world.dim.TeleporterThaumcraft;

/**
 * Fixes players spawning at wrong positions (e.g. X=0 Y=60+ Z=0) when entering a Thaumcraft eldritch portal, and fixes
 * incomplete maze generation (gaps/missing walls) in the outer lands.
 *
 * <h3>Root causes</h3>
 *
 * <p>
 * <b>Wrong spawn position:</b> {@code TeleporterThaumcraft.placeInExistingPortal} scans for {@code blockEldritchPortal}
 * via {@code world.getBlock()}, which goes through {@code provideChunk()}. Hodgepodge's EntityGuard mixin returns
 * {@code EmptyChunk} for unloaded chunks while chunk loading is blocked (during most of the server tick when
 * {@code throttleChunkGeneration} or {@code preventChunkLoadingFromBlockUpdates} is active). With all chunks appearing
 * as air, the scan finds no portal block and falls through to {@code makePortal()}, which is a no-op in Thaumcraft. The
 * second scan also fails, leaving the player at their initial outer-lands spawn position (0, Y, 0).
 *
 * <p>
 * <b>Incomplete maze (missing sections):</b> The outer-lands maze is generated by {@code ThaumcraftWorldGenerator}
 * during chunk population. When chunk A is being populated, it may query blocks in neighbouring chunk B (e.g. to
 * connect corridor walls). If B is not yet loaded, {@code provideChunk(B)} → {@code loadChunk(B)} →
 * {@code originalLoadChunk(B)} → {@code DeferPopulation} fires with {@code populationDepth > 0} (we are already inside
 * A's population), so B's population is <em>deferred</em>. B is loaded with terrain only — no maze structure. The
 * blocks A's generator reads from B are all air/stone, causing the maze walls at the A–B border to be incomplete.
 * Subsequent ticks populate B correctly, but the blocks A already (did not) write to B's side remain missing.
 *
 * <h3>Fix</h3>
 *
 * <p>
 * The constructor injection permanently adds the outer-lands dimension ID to
 * {@link ChunkGenScheduler#excludeDimFromChunkThrottle(int)}, which:
 * <ul>
 * <li>{@link com.mitchej123.hodgepodge.mixins.early.minecraft.fastload.MixinChunkProviderServer_EntityGuard}:
 * {@code provideChunk()} always loads chunks normally (bypasses all guards).</li>
 * <li>{@link com.mitchej123.hodgepodge.mixins.early.minecraft.chunkloading.MixinWorldServer_PreventChunkLoading}:
 * entity/block-update ticking no longer suppresses {@code loadChunkOnProvideRequest}.</li>
 * <li>{@link com.mitchej123.hodgepodge.mixins.early.minecraft.fastload.MixinChunkProviderServer_DeferPopulation}:
 * population of chunks in this dimension is never deferred, even when called from within another population pass
 * ({@code populationDepth > 0}). This allows full synchronous cascading population, ensuring the maze is always
 * complete at chunk borders.</li>
 * </ul>
 *
 * <p>
 * The {@code placeInPortal} HEAD/RETURN injections are retained as belt-and-suspenders: they additionally unblock the
 * global {@link ChunkGenScheduler} flag and restore {@code loadChunkOnProvideRequest}, and proactively force-load and
 * force-populate the entity's chunk before the scan. For excluded dimensions these are largely redundant but harmless.
 */
@Mixin(value = TeleporterThaumcraft.class, remap = false)
public class MixinTeleporterThaumcraft_PortalFix {

    @Shadow(remap = false)
    private WorldServer worldServerInstance;

    @Unique
    private boolean hodgepodge$wasChunkLoadBlocked;

    @Unique
    private boolean hodgepodge$wasLoadChunkOnProvideRequestDisabled;

    /**
     * Register the outer-lands dimension as excluded from chunk-load throttling. This fires once per teleporter
     * instance (i.e. when the outer-lands world is first accessed), permanently adding the dimension ID to the
     * exclusion set so that all subsequent chunk operations in that dimension bypass the throttle guards.
     */
    @Inject(method = "<init>", at = @At("RETURN"))
    private void hodgepodge$registerOuterLandsDim(WorldServer worldServer, CallbackInfo ci) {
        ChunkGenScheduler.excludeDimFromChunkThrottle(worldServer.provider.dimensionId);
    }

    @Inject(method = "placeInPortal", at = @At("HEAD"))
    private void hodgepodge$unblockForPortalSearch(Entity entity, double x, double y, double z, float yaw,
            CallbackInfo ci) {
        hodgepodge$wasChunkLoadBlocked = ChunkGenScheduler.isBlocked();
        if (hodgepodge$wasChunkLoadBlocked) {
            ChunkGenScheduler.enableChunkLoads();
        }

        final ChunkProviderServer cps = worldServerInstance.theChunkProviderServer;
        hodgepodge$wasLoadChunkOnProvideRequestDisabled = !cps.loadChunkOnProvideRequest;
        if (hodgepodge$wasLoadChunkOnProvideRequestDisabled) {
            cps.loadChunkOnProvideRequest = true;
        }

        // Proactively force-load and force-populate the chunk at the entity's destination position so that the
        // outer-lands portal room (including blockEldritchPortal at Y=53) is in place before the scan begins.
        final int cx = ((int) Math.floor(entity.posX)) >> 4;
        final int cz = ((int) Math.floor(entity.posZ)) >> 4;
        cps.loadChunk(cx, cz);
        cps.populate(cps, cx, cz);
    }

    @Inject(method = "placeInPortal", at = @At("RETURN"))
    private void hodgepodge$reblockAfterPortalSearch(Entity entity, double x, double y, double z, float yaw,
            CallbackInfo ci) {
        if (hodgepodge$wasChunkLoadBlocked) {
            ChunkGenScheduler.disableChunkLoads();
        }
        if (hodgepodge$wasLoadChunkOnProvideRequestDisabled) {
            worldServerInstance.theChunkProviderServer.loadChunkOnProvideRequest = false;
        }
    }
}
