name=Hodgepodge
version=${version}
additionalVersions=
className=com.mitchej123.hodgepodge.core.rfb.HodgepodgeRfbPlugin
transformerExclusions=com.mitchej123.hodgepodge.core.shared
versionConstraints=
loadBefore=
loadAfter=mixin
loadRequires=gtnhlib
